17.0 migration sale partner source
natuan9/sale-workflow pull request #2
Opened 2024-10-24 10:02 UTC by natuan9

2024-10-24 10:22 UTC, thienvh332 requested changes
After the change, the redundant data also needs to be cleaned. 
  

>  Hint, use **`upgrade_utils`** to do that.

2024-10-24 10:22 UTC, thienvh332 commented on sale_partner_source/hooks.py
> +    """)
field name in **utm.source** model is a unique constraint field. Have you considered the case of inserting duplicate name?

2024-10-24 10:22 UTC, thienvh332 commented on sale_partner_source/hooks.py
> +    """)
One more thing, we will migrate data from **`partner.category`** model and **`gts_partner_category`** module. Not from **`partner.classification`**

2024-10-24 10:22 UTC, thienvh332 commented on sale_partner_source/hooks.py
> +            JOIN partner_classification pc ON rp.partner_classification_id = pc.id
Same here

2024-10-24 10:24 UTC, thienvh332 commented on sale_partner_source/hooks.py
> +            JOIN partner_classification pc ON rp.partner_classification_id = pc.id
Sometimes we have to rearrange the order of the commands rather than trusting third party software and confusing others. :wink:

2024-11-04 11:26 UTC, nilshamerlinck commented on sale_partner_source/models/sale_order.py
> +    @api.model
I see a warning:

> 2024-11-04 07:40:22,776 166 WARNING rededition-staging-16245102 odoo.api.create: The model odoo.addons.sale_partner_utm_source.models.sale_order is not overriding the create method in batch

2024-12-03 10:07 UTC, closed without merging